# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movie Database' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxCocoa'
  pod 'RxSwift'

  target 'Movie DatabaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Movie DatabaseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
